### ISSUE TITLE
Use as base for IHaskell app?

### ISSUE THREAD

**Issue by gibiansky** [liyanage/ipython-notebook#11]
Hey there!

I'd like to use this as a base for an IHaskell app. Effectively, I'd like to use this awesome application but substitute in the Haskell GHC kernel instead of Python. My plan is to fork this, then figure out how to bundle the GHC compiler with it, and clean up all the shell scripts to install what I need for Haskell instead of Python (since I wouldn't need anything along the lines of OpenCV or SciPy). 

Is there anything you'd like me to do differently? The LICENSE specifies that I should use different artwork, so I will do that.

**Comment by liyanage** [comment]
Hi, your plan as outlined sounds good to me. Good luck with your project!
