### ISSUE TITLE
Can't install third-party packages

### ISSUE THREAD

**Issue by sburns** [liyanage/ipython-notebook#2]
This is really cool.

Hacking around a little bit…

``` bash
$ cd /Applications/IPython Notebook.app/Contents/Resources/virtualenv
$ source bin/activate
$ which pip
/usr/local/share/python/pip
```

:frowning: 

Your hands might be tied here w/ OS X code signing/gatekeeper/etc?

**Comment by sburns** [comment]
Also:

``` bash
cd /Applications/IPython Notebook.app/Contents/Resources/virtualenv
bin/pip install requests
-bash: bin/pip: /Users/liyanage/Library/Developer/Xcode/DerivedData/IPython_Notebook-btlftgkey: bad interpreter: No such file or directory
```

It'd be really neat if that worked. Probably wouldn't be portable across machines, though maybe if we limit to just Mountain Lion.

**Comment by liyanage** [comment]
Hey Scott,

I clearly don't expect people to modify that virtualenv because it would break the code signature. However, I am still surprised that the pip command it picks up is not the one inside the virtualenv, I think that works on my machine.

The virtualenv should be configured to also search in the system-wide environment, so if people want to add more modules, they could just use the system-wide install.

**Comment by sburns** [comment]
> The virtualenv should be configured to also search in the system-wide environment, so if people want to add more modules, they could just use the system-wide install.

I think the consensus is that using the system python is a bad idea. The app doesn't not pick up on my homebrew'd version.

``` bash
$ which python
/usr/local/bin/python
$ which pip
/usr/local/share/python/pip
$ pip freeze -l
distribute==0.6.35
ipython==0.13.1
numpy==1.7.0
pyzmq==13.0.0
requests==1.1.0
stevedore==0.8
tornado==2.4.1
virtualenv==1.9.1
virtualenv-clone==0.2.4
virtualenvwrapper==3.6
wsgiref==0.1.2
```

and 

![Screenshot 2013-03-12 at 3 08 31 PM](https://f.cloud.github.com/assets/440820/250662/a9ede298-8b50-11e2-91b0-53fa6ff4364a.PNG)

How feasible would it be to allow the user to specify a `site-packages` directory through a preference pane?

**Comment by liyanage** [comment]
Hi Scott,

> > How feasible would it be to allow the user to specify a site-packages directory through a preference pane?

Very feasible, and it seems that would solve it for a lot of people. I just suggested something like this in a message to the ipython-user mailing list. I will try how well that works on my system and probably implement it soon.

Thanks for taking the time to play with this and providing valuable feedback!

-Marc

**Comment by liyanage** [comment]
Try the most recent version (1.4), it includes a new Preferences area for adding items to the PYTHONPATH.

Launching the current version should offer an auto-update to 1.4.

**Comment by sburns** [comment]
Works like a charm with one tiny gotcha that isn't your fault. 

If you have "editable" packages installed with `pip install -e PACKAGE` within your virtualenv, these aren't importable because there's only an `*.egg-link` file in the `site-packages` directory.

This isn't your problem though and this issue is closed. Thanks for the good work!

**Comment by liyanage** [comment]
Thanks for trying it out, glad to hear it works for the common case!

I wonder if those editable packages could be made to work as well if you additionally give the app permission to read the egg-link's destination location, where the actual code is? You would do that in the upper of those two boxes in the Preferences window.
