### ISSUE TITLE
can't run system command "!" (bash magic)

### ISSUE THREAD

**Issue by epifanio** [liyanage/ipython-notebook#3]
Tring to run sytem (bash) commands like : 
ls
or other command  with the "!" prefix

i got this error : https://gist.github.com/epifanio/5148696

cd dir
pwd

are working fine instead

**Comment by liyanage** [comment]
Can you try this again in the 1.6 beta? You can get it here:

https://github.com/liyanage/ipython-notebook/releases/tag/v1.6-beta.1

At least `!ls` seems to work for me:

![screen shot 2013-10-31 at 12 37 42 pm](https://f.cloud.github.com/assets/52640/1449180/ffc9e7f0-4263-11e3-8d72-1e40d1316ab4.png)

**Comment by liyanage** [comment]
No reply, closing. Please open a new issue if you still see this in 1.10 or higher.
