### ISSUE TITLE
`Open` button doesn't work

### ISSUE THREAD

**Issue by mlhamel** [liyanage/ipython-notebook#6]
It seems i cannot used the `open` button from the File dropdown menu, When clicking on it, it just do nothing !

**Comment by liyanage** [comment]
Thanks for the report, that button and some others are supposed to be hidden because they don't work well in the standalone app context or are redundant with the app's menu commands.

The hiding is based on JavaScript and the HTML of the notebook changed in 1.0, so I need to adjust that.

**Comment by liyanage** [comment]
Fix is in this new release: https://github.com/liyanage/ipython-notebook/releases/tag/v1.6-beta.1
