### ISSUE TITLE
Spinning gear from startup never goes away

### ISSUE THREAD

**Issue by suchow** [liyanage/ipython-notebook#8]
![screen shot 2013-12-09 at 7 15 13 pm](https://f.cloud.github.com/assets/613981/1710403/4e5e7eae-6130-11e3-8580-c39a61f3245b.jpg)
![screen shot 2013-12-09 at 7 09 45 pm](https://f.cloud.github.com/assets/613981/1710404/539113e6-6130-11e3-91f1-3f9ac558cf17.jpg)

I'm on OS X 10.9, running version 1.10 of the notebook.

**Comment by liyanage** [comment]
I am trying to reproduce this, so far unsuccessfully. Do you have a set of steps that leads to this? How often do you see it? Is it related to your other issue #9?

**Comment by suchow** [comment]
Got it. Try this:
1. Open iPython Notebook.
2. While the loading screen is up, hide the app.
3. Wait a few seconds so that the app finishes loading.
4. Show the app.

**Comment by liyanage** [comment]
Awesome, that reproduces it here too, thanks! I would have never found those steps...

**Comment by liyanage** [comment]
Thanks again, the fix will be in the next release.
